/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package layout;

import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author antonid
 */
public class PenampilGambarComboBox extends javax.swing.JFrame {

    /**
     * Creates new form PenampilGambarComboBox
     */
    public PenampilGambarComboBox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxPanel = new javax.swing.JPanel();
        cbx = new javax.swing.JComboBox<>();
        imgPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblMS = new javax.swing.JLabel();
        lblMP = new javax.swing.JLabel();
        lblBotan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Penampil Gambar dengan ComboBox");

        cbxPanel.setBackground(new java.awt.Color(255, 255, 255));

        cbx.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        cbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clear", "MS", "MP", "Botan", "Exit" }));
        cbx.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxItemStateChanged(evt);
            }
        });
        cbxPanel.add(cbx);

        getContentPane().add(cbxPanel, java.awt.BorderLayout.PAGE_START);

        imgPanel.setBackground(new java.awt.Color(204, 204, 204));
        imgPanel.setLayout(new java.awt.CardLayout());
        imgPanel.add(jLabel1, "0");
        jLabel1.getAccessibleContext().setAccessibleName("0");

        lblMS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MS.png"))); // NOI18N
        imgPanel.add(lblMS, "1");
        lblMS.getAccessibleContext().setAccessibleName("1");

        lblMP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MP.jpg"))); // NOI18N
        imgPanel.add(lblMP, "2");
        lblMP.getAccessibleContext().setAccessibleName("2");

        lblBotan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBotan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Botan.png"))); // NOI18N
        imgPanel.add(lblBotan, "3");
        lblBotan.getAccessibleContext().setAccessibleName("3");

        getContentPane().add(imgPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxItemStateChanged
        // TODO add your handling code here:
        String v = cbx.getSelectedItem().toString();
       
if (!v.equals("Exit")){    
        CardLayout cl =(CardLayout) (imgPanel.getLayout());
        cl.show (imgPanel, String.valueOf(cbx.getSelectedIndex()));
    }else{
        
    int keluar = JOptionPane.showConfirmDialog(this, "Apakah Yakin Ingin Keluar", "keluar", JOptionPane.YES_NO_OPTION);
    if(keluar == 0){
     System.exit(0);
        }
    }//GEN-LAST:event_cbxItemStateChanged
}
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenampilGambarComboBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbx;
    private javax.swing.JPanel cbxPanel;
    private javax.swing.JPanel imgPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBotan;
    private javax.swing.JLabel lblMP;
    private javax.swing.JLabel lblMS;
    // End of variables declaration//GEN-END:variables
}
